
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 27;
  public static final int FUNCTION = 12;
  public static final int POWER = 28;
  public static final int ASSIGNMENT = 26;
  public static final int UMINUS = 5;
  public static final int INTEGER = 40;
  public static final int NOTEQUAL = 33;
  public static final int GREATER = 36;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int REALVAL = 41;
  public static final int ENDDO = 20;
  public static final int LESS = 34;
  public static final int FOR = 23;
  public static final int MINUS = 4;
  public static final int WRITE = 47;
  public static final int RPAREN = 8;
  public static final int DRAW = 50;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int ENDFUNCTION = 13;
  public static final int OR = 31;
  public static final int COMMA = 10;
  public static final int ENDFOR = 25;
  public static final int ENDPROGRAM = 22;
  public static final int PLUS = 3;
  public static final int LESSEQ = 35;
  public static final int IF = 14;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 9;
  public static final int error = 1;
  public static final int PROGRAM = 21;
  public static final int NUMBER = 39;
  public static final int MOD = 29;
  public static final int SET_LINE = 52;
  public static final int EQ = 38;
  public static final int SET_COLOR = 51;
  public static final int REAL = 42;
  public static final int MOVE = 49;
  public static final int TIMES = 6;
  public static final int LITERAL = 43;
  public static final int ENDIF = 17;
  public static final int ELSE = 16;
  public static final int READ = 46;
  public static final int TO = 24;
  public static final int WHILE = 18;
  public static final int CLEAR = 48;
  public static final int THEN = 15;
  public static final int STRING = 45;
  public static final int GREATEREQ = 37;
  public static final int DO = 19;
  public static final int IDENTIFIER = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "EQUAL",
  "COMMA",
  "RETURN",
  "FUNCTION",
  "ENDFUNCTION",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDDO",
  "PROGRAM",
  "ENDPROGRAM",
  "FOR",
  "TO",
  "ENDFOR",
  "ASSIGNMENT",
  "DIVIDE",
  "POWER",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "NOTEQUAL",
  "LESS",
  "LESSEQ",
  "GREATER",
  "GREATEREQ",
  "EQ",
  "NUMBER",
  "INTEGER",
  "REALVAL",
  "REAL",
  "LITERAL",
  "IDENTIFIER",
  "STRING",
  "READ",
  "WRITE",
  "CLEAR",
  "MOVE",
  "DRAW",
  "SET_COLOR",
  "SET_LINE"
  };
}

